name: Release Pexa

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          # will enable this eventually
          generate_release_notes: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
